version: '3.8'

volumes:
  postgres-data:
  mongodb-data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  server:
    build: .
    image: quabynah1809/quantia-go-banking:latest
    restart: always
    ports:
      - "3333:3333"
      - "3334:3334"
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/postgres
      - HTTP_PORT=3333
      - GRPC_PORT=3334
    depends_on:
      - postgres
      - mongodb
